name: Build deploy Job
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Install node_modules
        run: yarn
      - name: Creating .env file
        run: |
          echo NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL}} >> .env
      - name: Build the project
        run: yarn build
      - name: Listing files and remove node_modules
        run: |
          ls -a
          rm -rf node_modules
      - name: Deploy with rsync
        run: |
          rsync -avz * root@${{ secrets.SSH_HOST }}:./web
          rsync -avz .env root@${{ secrets.SSH_HOST }}:./web
          rsync -avz .next root@${{ secrets.SSH_HOST }}:./web
      - name: Executing cmd on remote
        run: |
          echo 'Installing node_modules'
          ssh -y root@${{ secrets.SSH_HOST }} 'cd web && yarn'
          echo 'Installing pm2'
          ssh -y root@${{ secrets.SSH_HOST }} 'yarn global add pm2'
          echo 'Starting pm2 web'
          ssh -y root@${{ secrets.SSH_HOST }} 'cd ~/web && pm2 restart wordix-web'
          ssh -y root@${{ secrets.SSH_HOST }} 'pm2 startup systemd'
          ssh -y root@${{ secrets.SSH_HOST }} 'pm2 save'
      - name: Setup finish
        run: echo "Setup Finished!"
